services:
  pytorch-tutorial:
    container_name: pytorch-tutorial
    build: 
      context: ./environment
      dockerfile: Dockerfile
    volumes:
      - ./src:/home/workdir/src
      - .env:/home/workdir/.env
    tty: true
    environment:
      - PYTHONPATH=/home/workdir/src
