version: '3'

services:
  analyse:
    container_name: analyse
    build: 
      context: ./environment
      dockerfile: Dockerfile.mlenv
    volumes:
      - ./src:/home/workdir/src
      - ./data:/home/workdir/data
      - ./models:/home/workdir/models
      - ./logs:/home/workdir/logs
      - .env:/home/workdir/.env
    tty: true
    environment:
      - PYTHONPATH=/home/workdir/src
